#import <Foundation/Foundation.h>

@interface Constants : NSObject

FOUNDATION_EXPORT NSString *const FETCH_HOME_TIMELINE_URL;
FOUNDATION_EXPORT NSString *const FETCH_USER_PROFILE_URL;
FOUNDATION_EXPORT NSString *const POST_TWEET_URL;
FOUNDATION_EXPORT NSString *const FETCH_FOLLOWERS_URL;
FOUNDATION_EXPORT NSString *const FETCH_FRIENDS_URL;

@end
